version: '3'

services:
  postgres:
    image: postgres:14.6-alpine
    container_name: label-stick-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  object-storage:
    image: chrislusf/seaweedfs:3.47
    container_name: label-stick-object-storage
    command:
      [
        "server",
        "-s3",
        "-volume.max",
        "8",
        "-master.volumeSizeLimitMB",
        "10"
      ]
    ports:
      - 8333:8333
      - 8888:8888
      - 8080:8080
      - 9333:9333
    volumes:
      - ./data/seaweedfs-data/data:/data
      - ./data/seaweedfs-data/buckets:/buckets

  redis:
    image: redis:6.2.6-alpine
    container_name: label-stick-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data

  service-user:
    container_name: service-user
    build: ./label-stick-be/service-user
    ports:
      - "8010:8010"
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8010"
      - "--reload"
    volumes:
      - ./label-stick-be/service-user:/app/service-user
    environment:
      - POSTGRES_SERVER=postgres
    # depends_on:
    #   - postgres

  service-manager:
    container_name: service-manager
    build: ./label-stick-be/service-manager
    ports:
      - "8020:8020"
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8020"
      - "--reload"
    volumes:
      - ./label-stick-be/service-manager:/app/service-manager
    environment:
      - POSTGRES_SERVER=postgres
      - STORAGE_HOST=object-storage
      - REDIS_HOST=redis
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/1
    # depends_on:
    #   - postgres

  service-label:
    container_name: service-label
    build: ./label-stick-be/service-label
    ports:
      - "8030:8030"
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8030"
      - "--reload"
    volumes:
      - ./label-stick-be/service-label:/app/service-label
    environment:
      - POSTGRES_SERVER=postgres

  service-gateway:
    container_name: service-gateway
    build: ./label-stick-be/service-gateway
    ports:
      - "8000:8000"
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reload"
    volumes:
      - ./label-stick-be/service-gateway:/app/service-gateway
    environment:
      - USER_SERVICE_URL=http://service-user:8010
      - MANAGER_SERVICE_URL=http://service-manager:8020
      - LABEL_SERVICE_URL=http://service-label:8030

  service-worker:
    container_name: service-worker
    build: ./label-stick-be/service-worker
    working_dir: /app/service-worker
    command: "celery -A tasks worker -P solo -c 4 --loglevel=info"
    environment:
      - REDIS_HOST=redis
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/1
  # fe:
  #   container_name: label-stick-fe
  #   build: ./label-stick-fe
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./label-stick-fe/dist:/usr/share/nginx/html
