version: '3'

services:
  postgres:
    image: postgres:14.6-alpine
    container_name: label-stick-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  object-storage:
    image: chrislusf/seaweedfs:3.47
    container_name: label-stick-object-storage
    command:
      [
        "server",
        "-s3",
        "-volume.max",
        "8",
        "-master.volumeSizeLimitMB",
        "10"
      ]
    ports:
      - 8333:8333
      - 8888:8888
      - 8080:8080
      - 9333:9333
    volumes:
      - ./data/seaweedfs-data/data:/data
      - ./data/seaweedfs-data/buckets:/buckets

  redis:
    image: redis:6.2.6-alpine
    container_name: label-stick-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data

  service-user:
    container_name: label-stick-service-user
    build: ./label-stick-be/service-user
    ports:
      - "8010:8010"
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8010"
      - "--reload"
    volumes:
      - ./label-stick-be/service-user:/app/service-user
    environment:
      - POSTGRES_SERVER=postgres
    depends_on:
      - postgres

  service-manager:
    container_name: label-stick-service-manager
    build: ./label-stick-be/service-manager
    ports:
      - "8010:8010"
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8010"
      - "--reload"
    volumes:
      - ./label-stick-be/service-manager:/app/service-manager
    environment:
      - POSTGRES_SERVER=postgres
      - STORAGE_HOST=object-storage
    depends_on:
      - postgres

  service-label:
    container_name: label-stick-service-label
    build: ./label-stick-be/service-label
    ports:
      - "8010:8010"
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8010"
      - "--reload"
    volumes:
      - ./label-stick-be/service-label:/app/service-label
    environment:
      - POSTGRES_SERVER=postgres
    depends_on:
      - postgres

  service-gateway:
    container_name: label-stick-service-gateway
    build: ./label-stick-be/service-gateway
    ports:
      - "8000:8000"
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reload"
    volumes:
      - ./label-stick-be/service-gateway:/app/service-gateway
    depends_on:
      - postgres

  service-worker:
    container_name: service-worker
    build: ./service-worker
    ports:
      - "8011:8011"
    working_dir: /app/service-worker
    command: "celery -A tasks worker -P solo -c 4 --loglevel=info"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  label-stick-fe:
    container_name: label-stick-fe
    build: ./label-stick-fe
    ports:
      - "3000:3000"
