"""name unique

Revision ID: 2
Revises: 1
Create Date: 2023-07-06 00:11:35.532616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignments_name_key', 'assignments', type_='unique')
    op.drop_constraint('labels_name_key', 'labels', type_='unique')
    op.drop_constraint('projects_name_key', 'projects', type_='unique')
    op.drop_constraint('sentences_name_key', 'sentences', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('sentences_name_key', 'sentences', ['name'])
    op.create_unique_constraint('projects_name_key', 'projects', ['name'])
    op.create_unique_constraint('labels_name_key', 'labels', ['name'])
    op.create_unique_constraint('assignments_name_key', 'assignments', ['name'])
    # ### end Alembic commands ###
