"""sentence label unique

Revision ID: 3
Revises: 2
Create Date: 2023-07-07 16:46:51.319625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'label_sentences', ['sentence_id', 'label_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'label_sentences', type_='unique')
    # ### end Alembic commands ###
